### ISSUE TITLE
Be able to filter the leaderboard to more specific domains

### ISSUE THREAD

**Issue by epijim** [openpharma/opensource_dashboard#4]
The current leaderboard is fantastic as a big picture - but would be really interesting if (once the pharmaverse packages are available) we could filter this page to show what it looks like with just the core pharmaverse packages (e.g. removing all the scientific packages, to just leave the backbone of clinical reporting).

**Comment by MathieuCayssol** [comment]
I've added it. Tell me if it makes sense for you.

I don't really like the way of switching from all packages to pharmaverse, but I don't have other solutions with core components of streamlit. (https://docs.streamlit.io/library/api-reference/widgets)

<img width="1209" alt="Capture d’écran 2022-07-19 à 16 21 02" src="https://user-images.githubusercontent.com/49449000/179773662-60cebd4c-8a22-4ddb-8dcb-16ec17f4dfd7.png">
